### ISSUE TITLE
parser: SyntaxError with colon search

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-query-parser#16]
@jmartinm reports:
[...]
The following search:

```
035__a:oai:arXiv.org:1503.06238
```

which is being used [here](https://github.com/inveniosoftware/invenio/blob/master/invenio/ext/arxiv/__init__.py#L161) breaks the search engine:

https://gist.github.com/anonymous/cf4a997848a64c95ec2b
[...]

Superseeds inveniosoftware/invenio#2931

**Comment by jirikuncar** [comment]
IMHO correct search syntax should be: `035__a:"oai:arXiv.org:1503.06238"`

**Comment by tiborsimko** [comment]
> IMHO correct search syntax should be: 035__a:"oai:arXiv.org:1503.06238"

People often don't bother typing quote delimitators, which is why some "guessing" can be helpful in these cases.  E.g. `oai` is not a valid field or valid index, so it can be treated as part of the string value.  This is how this kind of situation was treated in Invenio v1.x parser.

**Comment by jirikuncar** [comment]
Unfortunately there is no nice solution if we want to support MARC field (any field) search. If we limit allowed keywords then we can implement it.

**Comment by jirikuncar** [comment]
Here there are some pointers if one would like to change the keyword search nesting:
- https://github.com/inveniosoftware/invenio-query-parser/blob/master/invenio_query_parser/parser.py#L188
- https://github.com/inveniosoftware/invenio-query-parser/blob/master/invenio_query_parser/parser.py#L198
- https://github.com/inveniosoftware/invenio-query-parser/blob/master/invenio_query_parser/parser.py#L163-L167

**Comment by tiborsimko** [comment]
> If we limit allowed keywords then we can implement it.

:+1: for sorting the problem for regular users by looking at allowed keywords.

As for MARC syntax in queries, these should be typically used only by cataloguers and other power users, and I assume these users can be asked to add required quote delimitors by themselves, without having to restort to guessing...

**Comment by jirikuncar** [comment]
> As for MARC syntax in queries

We can't have both "limited" keywords and any MARC field.

I think it's ok to ask users to "escape" colons that should not be used in keyword search.

**Comment by jirikuncar** [comment]
We could however plug in keywords that support nesting ([`NestedKeywords`](https://github.com/inveniosoftware/invenio-query-parser/blob/master/invenio_query_parser/parser.py#L163-L167)).

**Comment by tiborsimko** [comment]
> We can't have both "limited" keywords and any MARC field.

When seeing FIELD:VALUE, what about: (1) regular FIELD keywords are recognised from the usual allowed list "author", "title', etc; (2) otherwise if FIELD starts by two digits etc, it is recognised as MARC query; (3) otherwise the FIELD string is part of the VALUE, as it were.  The `oai` example would be in the third category.

**Comment by jirikuncar** [comment]
Personally I don't really like `if` in the grammar and special handling for MARC fields in parser. We can keep it open for "someday".

**Comment by jmartinm** [comment]
I can confirm that using:

```
035__a:"oai:arXiv.org:1503.06238"
```

At least does not crash the parser. The parser will have to be amended so that at least we don't crash the system as it is currently happening.

[See exception](https://gist.github.com/anonymous/cf4a997848a64c95ec2b)

**Comment by kaplun** [comment]
So we are thinking the best way would be to provide the parser with a callback that would be checked in order to decide if a given potential keyword is indeed a keyword or not.
