### ISSUE TITLE
spires: `whois` operator

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/invenio-query-parser#17]
Originally on 2012-01-30

In SPIRES query mode, a search for `whois ellis` should expand into `find name ellis` in HEPNames collection. This is easy to do, since `whois` operator cannot be apparently combined in Boolean queries and whatnot, so a simple query replacement will do.  The only complication not to forget is to alter the searched collection to HEPNames regardless of the starting collection the user originated his/her query from.

Original issue: inveniosoftware/invenio#877

**Comment by kaplun** [comment]
See #18
