### ISSUE TITLE
parser: query parser does not parse all possible combinations of NOT operator correctly

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-query-parser#24]
The `NOT` operator is not parsed as NotOp.

OR NOT
-----------
`NOT` is parsed as a `Value`.

**Example:**
`test AND (author:"Alexander, S" OR NOT author:"Costa, M S")`

gives

`AndOp(ValueQuery(Value('test')), AndOp(OrOp(KeywordOp(Keyword('author'), DoubleQuotedValue('Alexander, S')), ValueQuery(Value('NOT'))), KeywordOp(Keyword('author'), DoubleQuotedValue('Costa, M S'))))`

AND (NOT ...
-----------------
`NOT` is parsed as a `Value`.

**Example:**
`test AND (NOT author:"Alexander, S")`

gives

`AndOp(ValueQuery(Value('test')), AndOp(ValueQuery(Value('NOT')), KeywordOp(Keyword('author'), DoubleQuotedValue('Alexander, S'))))`

Only AND NOT works
-----------------------------
NOT is then properly parsed as NotOp

**Example:**

`test AND (author:"Alexander, S" AND NOT author:"Costa, M S")`

gives

`AndOp(ValueQuery(Value('test')), AndOp(KeywordOp(Keyword('author'), DoubleQuotedValue('Alexander, S')), NotOp(KeywordOp(Keyword('author'), DoubleQuotedValue('Costa, M S')))))`

If some operations are not supported like `OR NOT`, then server should return an error. It should not parse it sometime as a `Value` and sometime as `NotOp`.

previously reported as inveniosoftware/invenio#3366

**Comment by kaplun** [comment]
Similar issues appear when using `-`. E.g.:
* [ ] `-author`
```python
In [43]: parser.parse_query('-author')
Out[43]: ValueQuery(Value('-author'))
```
(should have been: `NotOp(ValueQuery(Value('author')))`)
* [ ] `-author:"catelan, m"` 
```python
In [42]: parser.parse_query('-author:"catelan, m"')             
  File "<string>", line 1
    -author:"catelan, m"
           ^
SyntaxError: expecting one of [<class 'invenio_query_parser.parser.NotQuery'>, <class 'invenio_query_parser.parser.AndQuery'>, <class 'invenio_query_parser.parser.OrQuery'>, <class 'invenio_query_parser.parser.ImplicitAndQuery'>]
```
(should have been: `NotOp(KeywordOp(Keyword('author'), DoubleQuotedValue('catelan, m')))`)
* [ ] `salamanca | -author:"catelan, m"`
```python
In [50]: parser.parse_query('salamanca | -author:"catelan, m"')
  File "<string>", line 1
    salamanca | -author:"catelan, m"
                      ^
SyntaxError: expecting one of [<class 'invenio_query_parser.parser.NotQuery'>, <class 'invenio_query_parser.parser.AndQuery'>, <class 'invenio_query_parser.parser.OrQuery'>, <class 'invenio_query_parser.parser.ImplicitAndQuery'>]
```
(should have been: `OrOp(ValueQuery(Value('salamanca')), NotOp(KeywordOp(Keyword('author'), DoubleQuotedValue('catelan, m'))))`)
