### ISSUE TITLE
spires: syntax converter parenthesis bug

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-query-parser#32]
In inspirehep/invenio#71 @tsgit reports:
[...]
these 2 searches
`find collaboration LIGO and a whiting, b f and a Weiss, r`
`find collaboration LIGO and (a whiting, b f and a Weiss, r)`
return vastly different results (90 vs 152 records)

this is because 
`find collaboration LIGO and (a whiting, b f and a Weiss, r)`
is incorrectly converted to
`collaboration:LIGO and ((author:"whiting, b* f*") and (author:"Weiss, r)*" or exactauthor:"Weiss, r *" or exactauthor:"Weiss, r" or author:"Weiss, r), *")`

where you see the closing paren becomes part of the author search term. Invenio search then ignores all parens, since they are mismatched, the warning message is

`"Search syntax misunderstood. Ignoring all parentheses in the query. If this doesn't help, please check your search and try again."`

so now we have a *boolean or* search for `Weiss, r` which finds additional records. The underlying problem is *spires-to-inveno* syntax conversion's handling of the parenthesized expression.
[...]

**Comment by kaplun** [comment]
This is probably working in `invenio-query-parser`. In that case it can be closed.

**Comment by jirikuncar** [comment]
> This is probably working ...

The best way is to add test cases for it ... it should be just a copy&paste from the issue :clipboard:

**Comment by kaplun** [comment]
@Panos512 can you have a look?

**Comment by Panos512** [comment]
@kaplun Sure, right away!

**Comment by Panos512** [comment]
`find collaboration LIGO and a whiting, b f and a Weiss, r`
parses as: `find (collaboration LIGO and a whiting, b f) and a Weiss, r`

This is a convention we have to make since 'and' is a binary operator.
So the results are logically correct.
I will create a couple of test cases and commit them.

**Comment by kaplun** [comment]
Excellent. As you can see in the original ticket the problem with the legacy parser was that the parentheses where really eaten up in the wrong way. So it's good to prove that the new parser works as it should in the above conditions.
