### ISSUE TITLE
ES query parser inconsistency comparing to Q on empty string and no parameters

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/invenio-query-parser#64]
I don't know if this is a bug or a planned design, but if you compare the IQ function from `invenio_query_parser.contrib.elasticsearch` and the standard Q function from `elasticsearch_dsl.query` there is a difference on how they behave when initialized without parameters and with empty string.
```python
from elasticsearch_dsl.query import Q
Q()
# MatchAll()

from invenio_query_parser.contrib.elasticsearch import IQ
IQ()
# TypeError: invenio_query() missing 1 required positional argument: 'pattern'
```

and
```python
from elasticsearch_dsl.query import Q
Q('') 
# ** elasticsearch_dsl.exceptions.UnknownDslObject: DSL class `` does not exist in query.

from invenio_query_parser.contrib.elasticsearch import IQ
IQ('')
# MatchAll()
```

would it make sense to make the IQ behave the same way as Q?

**Comment by jirikuncar** [comment]
- `from elasticsearch_dsl.query import Q` is a query representation
- `from invenio_query_parser.contrib.elasticsearch import IQ` is a parser

**Comment by switowski** [comment]
Ahh, good point. Thank you for the explanation!
